version: "3"
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes: 
      - /home/site_results_wfs:/srv/jekyll:z
      - /home/site_results_wfs/vendor/bundle:/usr/local/bundle:z
    ports:
      - 4000:4000
    networks:
      - geold
  nginx: 
    image: nginx 
    ports:
      - 80:80
    networks:
      - geold
  webgeold:
    image: webgeold
    ports: 
      - 8081:8081
    networks:
      - geold
  graphdb:
    image: graphdb-free
    volumes:
      - /var/run/docker/volumes/graphdbvol/_data:/graphdb/data:z
    ports:
      - 7200:7200
    networks:
     - geold 
networks:
  geold:
    driver: "bridge"
